OPTIONS (SKIP=1)

LOAD DATA
INFILE 'transactions_sample.csv'
BADFILE 'load.bad'
DISCARDFILE 'load.dsc'
APPEND
INTO TABLE TRANSACTIONS
WHEN TXN_STATUS = 'SUCCESS'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    FROM_WALLET_ID,
    TO_WALLET_ID,
    COIN_ID,
    AMOUNT,
    FEE,
    TXN_STATUS,
    TXN_TIMESTAMP DATE "YYYY-MM-DD HH24:MI:SS",
    NOTES
)